name: Ultroid Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_ID: 22057635
      API_HASH: d4624448590c0f3e702849f9d4e25f2b
      SESSION: 1BVtsOIUBu8CNYi7TsuUd0e6AgXOtSricUiu0t_j_o5MCQtyNJTNOLus35y0SLZxXWcNJfZ-TdK8t73nI36og8Gz89byVRw-pzPfMMm6DXQLh-eKEi2gwCG-Kmt6u2hTWOBgrV7FhFpdFVXXonMGaKetJVK9m0rvOVpI-2DlyV-bw_Vx_eq4ANCYG7g1bxr72SBSFOiBHO__shCSWh8C-ITKYajBhXLapX0totvSjqggiwNm4Ml1yFWzoVgJQp3JVUgLlHEimxW0bkzU2Pl22f8vlEHyq0z-pvVW08hcWv2HU4mKMdDZVBZvIJMhF9a_N5ZAmzr37FuCxflVBIooqZ5rGNQlsBco=
      REDIS_URI: redis-13407.c80.us-east-1-2.ec2.redns.redis-cloud.com:13407
      REDIS_PASSWORD: cQ6lNU5D50kZ0evlJATL7IMZcq1lsGoV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run Ultroid
        run: |
          python3 -m pyUltroid
